// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iortcrrfdkfiudbxunya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcnRjcnJmZGtmaXVkYnh1bnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA4MTIsImV4cCI6MjA2NTU0NjgxMn0.Tw1oFP3hDJgNHY_QRwItdRhX80VHk-mJHrOgWPok4G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);